DOMAIN = "ha_energy_native_clone"
ASSET_VERSION = "2026.06.22.49"

DEFAULT_TITLE = "Energie Native"
DEFAULT_ICON = "mdi:lightning-bolt-circle"
DEFAULT_URL_PATH = "energy-native-clone"
DEFAULT_ADMIN_ONLY = False

PANEL_COMPONENT_NAME = "ha-energy-native-clone-panel"
PANEL_FILENAME = "panel.js"
PANEL_STATIC_PATH = f"/{DOMAIN}/{PANEL_FILENAME}"
PANEL_STATIC_URL = f"{PANEL_STATIC_PATH}?v={ASSET_VERSION}"
LIVE_DISTRIBUTION_FILENAME = "live-distribution-card.js"
LIVE_DISTRIBUTION_STATIC_PATH = f"/{DOMAIN}/{LIVE_DISTRIBUTION_FILENAME}"
LIVE_DISTRIBUTION_STATIC_URL = f"{LIVE_DISTRIBUTION_STATIC_PATH}?v={ASSET_VERSION}"
POWER_FLOW_FILENAME = "power-flow-card.js"
POWER_FLOW_STATIC_PATH = f"/{DOMAIN}/{POWER_FLOW_FILENAME}"
POWER_FLOW_STATIC_URL = f"{POWER_FLOW_STATIC_PATH}?v={ASSET_VERSION}"
ENERGY_FLOW_PLUS_FILENAME = "energy-flow-card-plus.js"
ENERGY_FLOW_PLUS_STATIC_PATH = f"/{DOMAIN}/{ENERGY_FLOW_PLUS_FILENAME}"
ENERGY_FLOW_PLUS_STATIC_URL = f"{ENERGY_FLOW_PLUS_STATIC_PATH}?v={ASSET_VERSION}"

STORAGE_VERSION = 1
STORAGE_KEY = f"{DOMAIN}_settings"
